<?php
declare(strict_types=1);
require_once __DIR__.'/lib/Harness.php';
foreach(['Routing','Features','Policy','Codec','Auth','Store','Cluster','Broker','Metadata','HttpMetadata']as$class)require_once dirname(__DIR__).'/src/'.$class.'.php';
function hmBroker():Broker{$dir=sys_get_temp_dir().'/qf-http-meta-test-'.bin2hex(random_bytes(6));$b=new Broker(new Store($dir.'/messages.log'),$dir.'/users.json');$b->bootstrap('devpassword12');return$b;}
function hmApply(Broker$b,array$stage):void{foreach($stage['commands']as$command)$b->applyRaft('meta',$command['kind'],$command['data'],0);}
function hmReject(Broker$b,string$method,string$path,array$json,string$label):void{$before=$b->raftState('meta');$thrown=false;try{HttpMetadata::stage($b,$method,$path,$json);}catch(RuntimeException){$thrown=true;}Harness::ok($label.' rejected',$thrown);Harness::eq($label.' leaves live metadata',$before,$b->raftState('meta'));}
Harness::guard('users passwords and vhosts stage without live mutations',static function():void{
 $b=hmBroker();$before=$b->raftState('meta');$stage=HttpMetadata::stage($b,'PUT','/api/users/alice',['password'=>'password123','tags'=>'management, monitoring']);Harness::eq('user stage live untouched',$before,$b->raftState('meta'));Harness::eq('hash command kind','user',$stage['commands'][0]['kind']);Harness::ok('password is hashed',Auth::matches('password123',$stage['commands'][0]['data']['hash']));Harness::ok('plaintext absent',!str_contains(json_encode($stage['commands']),'password123'));hmApply($b,$stage);Harness::ok('committed login',$b->verify('alice','password123'));
 $stage=HttpMetadata::stage($b,'PUT','/api/vhosts/tenant',[]);Harness::ok('vhost invisible before commit',!in_array('tenant',$b->vhosts,true));hmApply($b,$stage);Harness::ok('vhost committed',in_array('tenant',$b->vhosts,true));
 hmReject($b,'PUT','/api/users/weak',['password'=>'short'],'weak password');hmReject($b,'PUT','/api/users/badhash',['password_hash'=>'bad'],'bad hash');hmReject($b,'DELETE','/api/vhosts/%2f',[],'default vhost delete');
 $stage=HttpMetadata::stage($b,'PUT','/api/permissions/tenant/alice',['configure'=>'.*','write'=>'^events$','read'=>'.*']);hmApply($b,$stage);Harness::eq('permission canonical vhost','^events$',$b->permissions['alice']['tenant']['write']);hmReject($b,'PUT','/api/permissions/tenant/alice',['write'=>'['],'permission regex');hmReject($b,'PUT','/api/permissions/missing/alice',[],'missing permission vhost');
});
Harness::guard('queue exchange and binding use strict protocol metadata',static function():void{
 $b=hmBroker();$b->vhosts[]='tenant';$s=HttpMetadata::stage($b,'PUT','/api/queues/tenant/q',['durable'=>true,'arguments'=>['x-queue-type'=>'stream']]);Harness::ok('queue not live',!isset($b->forVhost('tenant')->queues['q']));hmApply($b,$s);Harness::eq('stream queue type','stream',$b->forVhost('tenant')->queues['q']['args']['queueType']);Harness::ok('root vhost isolated',!isset($b->queues['q']));
 hmReject($b,'PUT','/api/queues/tenant/q',['durable'=>true,'arguments'=>['x-queue-type'=>'classic']],'inequivalent queue');hmReject($b,'PUT','/api/queues/tenant/invalid',['arguments'=>['x-message-ttl'=>-1]],'negative ttl');hmReject($b,'PUT','/api/queues/tenant/transient',['durable'=>false,'arguments'=>['x-queue-type'=>'quorum']],'transient quorum');hmReject($b,'PUT','/api/queues/tenant/exclusive',['exclusive'=>true],'exclusive management');
 $s=HttpMetadata::stage($b,'PUT','/api/exchanges/tenant/events',['type'=>'topic','durable'=>true]);hmApply($b,$s);$s=HttpMetadata::stage($b,'POST','/api/bindings/tenant/e/events/q/q',['routing_key'=>'key.#']);Harness::eq('binding not yet live',0,count($b->forVhost('tenant')->bindings));hmApply($b,$s);Harness::eq('binding committed','key.#',$b->forVhost('tenant')->bindings[0]['key']);hmReject($b,'PUT','/api/exchanges/tenant/events',['type'=>'direct'],'inequivalent exchange');hmReject($b,'POST','/api/bindings/tenant/e/missing/q/q',[],'missing binding source');
 $s=HttpMetadata::stage($b,'DELETE','/api/bindings/tenant/e/events/q/q/key.%23',[]);hmApply($b,$s);Harness::eq('binding delete committed',[],$b->forVhost('tenant')->bindings);
 $s=HttpMetadata::stage($b,'DELETE','/api/queues/tenant/q',[]);hmApply($b,$s);Harness::ok('queue delete committed',!isset($b->forVhost('tenant')->queues['q']));
});
Harness::guard('policy limits runtime parameters and topic permissions',static function():void{
 $b=hmBroker();hmApply($b,HttpMetadata::stage($b,'PUT','/api/policies/%2f/ttl',['pattern'=>'^q','definition'=>['message-ttl'=>10],'priority'=>2]));Harness::eq('canonical policy definition',10,$b->policies['/']['ttl']['definition']['message-ttl']);hmApply($b,HttpMetadata::stage($b,'PUT','/api/operator-policies/%2f/op',['pattern'=>'.*','definition'=>['max-length'=>5]]));Harness::eq('operator policy preserved',5,$b->operatorPolicies['/']['op']['definition']['max-length']);
 hmReject($b,'PUT','/api/policies/%2f/bad',['pattern'=>'[','definition'=>[]],'policy regex');hmReject($b,'PUT','/api/policies/%2f/bad',['pattern'=>'.*','definition'=>['message-ttl'=>'oops']],'policy ttl type');
 hmApply($b,HttpMetadata::stage($b,'PUT','/api/user-limits/admin/max-connections',['value'=>3]));hmApply($b,HttpMetadata::stage($b,'PUT','/api/user-limits/admin/max-channels',['value'=>4]));Harness::eq('limit update preserves siblings',3,$b->userLimits['admin']['max-connections']);hmApply($b,HttpMetadata::stage($b,'DELETE','/api/user-limits/admin/max-connections',[]));Harness::eq('limit delete preserves siblings',4,$b->userLimits['admin']['max-channels']);hmReject($b,'PUT','/api/vhost-limits/%2f/max-queues',['value'=>'4'],'limit type');
 hmApply($b,HttpMetadata::stage($b,'PUT','/api/parameters/federation-upstream/%2f/up',['value'=>['uri'=>'amqp:///other']]));Harness::eq('runtime parameter replicated','amqp:///other',$b->parameters['federation-upstream']['/']['up']['uri']);hmApply($b,HttpMetadata::stage($b,'PUT','/api/global-parameters/name',['value'=>null]));Harness::ok('null global parameter exists',array_key_exists('name',$b->parameters['global']['/']));
 hmApply($b,HttpMetadata::stage($b,'PUT','/api/topic-permissions/%2f/admin',['exchange'=>'amq.topic','write'=>'^one$','read'=>'.*']));Harness::eq('topic permission canonical','^one$',$b->topicPermissions['admin']['/']['amq.topic']['write']);hmApply($b,HttpMetadata::stage($b,'DELETE','/api/topic-permissions/%2f/admin/amq.topic',[]));Harness::ok('topic delete committed',!isset($b->topicPermissions['admin']['/']['amq.topic']));
});
Harness::guard('definitions ordered canonical atomic validation',static function():void{
 $b=hmBroker();$j=['vhosts'=>[['name'=>'tenant']],'users'=>[['name'=>'new','password_hash'=>Auth::hash('password123'),'tags'=>'management']],'queues'=>[['vhost'=>'tenant','name'=>'q','durable'=>true]],'exchanges'=>[['vhost'=>'tenant','name'=>'events','type'=>'topic','durable'=>true]],'bindings'=>[['vhost'=>'tenant','source'=>'events','destination'=>'q','destination_type'=>'queue','routing_key'=>'#']],'permissions'=>[['user'=>'new','vhost'=>'tenant','configure'=>'.*','write'=>'.*','read'=>'.*']]];
 $before=$b->raftState('meta');$s=HttpMetadata::stage($b,'POST','/api/definitions',$j);Harness::eq('definition staging live untouched',$before,$b->raftState('meta'));Harness::eq('canonical order',['vhost','user','exchange','queue','binding','permission'],array_column($s['commands'],'kind'));hmApply($b,$s);Harness::eq('imported topology scoped',1,count($b->forVhost('tenant')->bindings));Harness::ok('imported user credential',$b->verify('new','password123'));
 $invalid=['vhosts'=>[['name'=>'not-committed']],'queues'=>[['vhost'=>'not-committed','name'=>'bad','arguments'=>['x-queue-type'=>'unknown']]]];hmReject($b,'POST','/api/definitions',$invalid,'late definitions error');hmReject($b,'POST','/api/definitions',['mystery'=>[]],'unknown definitions field');
 $builtins=[];foreach($b->exchanges as$name=>$type)if($name===''||str_starts_with($name,'amq.'))$builtins[]=['name'=>$name,'vhost'=>'/','type'=>$type,'durable'=>$b->exchangeRows[$name]['durable']??true,'auto_delete'=>$b->exchangeRows[$name]['autoDelete']??false,'internal'=>$b->exchangeRows[$name]['internal']??false];$roundtrip=HttpMetadata::stage($b,'POST','/api/definitions',['exchanges'=>$builtins]);Harness::eq('exported builtins import read only',[],$roundtrip['commands']);hmReject($b,'POST','/api/definitions',['exchanges'=>[['name'=>'amq.direct','type'=>'fanout']]],'built-in mutation import');
 Harness::eq('publish bypasses metadata',null,HttpMetadata::stage($b,'POST','/api/exchanges/%2f/e/publish',[]));Harness::eq('get bypasses metadata',null,HttpMetadata::stage($b,'POST','/api/queues/%2f/q/get',[]));Harness::eq('shovel stays node local',null,HttpMetadata::stage($b,'PUT','/api/parameters/shovel/%2f/s',['value'=>[]]));
});
Harness::guard('live bodies conditional counts exclusive locks and temporary stores',static function():void{
 $b=hmBroker();$b->declareQueue('live');$b->publish(0,0,0,'','live',"must survive\0",2);$b->flushDurable();$bytes=file_get_contents($b->store->path);$streams=count(get_resources('stream'));
 $stage=HttpMetadata::stage($b,'DELETE','/api/queues/%2f/live',[]);Harness::eq('delete only staged','delete_queue',$stage['commands'][0]['kind']);Harness::eq('live log bytes unchanged',$bytes,file_get_contents($b->store->path));Harness::eq('live body still ready',1,$b->readyCount('live'));Harness::ok('scratch streams closed',count(get_resources('stream'))<=$streams);
 hmReject($b,'DELETE','/api/queues/%2f/live?if-empty=true',[],'conditional nonempty delete');
 $b->registerProtocolConsumer('live',55,'test',static fn()=>false,static function():void{});hmReject($b,'DELETE','/api/queues/%2f/live?if-unused=true',[],'conditional in-use delete');$b->unregisterProtocolConsumer('live',55,'test');
 $b->declareQueue('sac',['x-single-active-consumer'=>true]);$same=HttpMetadata::stage($b,'PUT','/api/queues/%2f/sac',['arguments'=>['x-single-active-consumer'=>true]]);Harness::eq('boolean equivalence survives snapshot',[],$same['commands']);
 $b->declareQueue('locked',[],false,true);hmReject($b,'DELETE','/api/queues/%2f/locked',[],'exclusive live queue delete');
 $b->declareExchange('events','topic');$legacy=HttpMetadata::stage($b,'POST','/api/bindings/%2f',['source'=>'events','destination'=>'live','routing_key'=>'x']);hmApply($b,$legacy);Harness::eq('legacy SPA binding canonical','x',$b->bindings[0]['key']);hmApply($b,HttpMetadata::stage($b,'DELETE','/api/bindings/%2f/events/live/x',[]));Harness::eq('legacy SPA unbind canonical',[],$b->bindings);
});
Harness::done();
