<?php
declare(strict_types=1);
require_once __DIR__.'/lib/Harness.php';
foreach(['Routing','Features','Policy','Codec','Auth','Store','Cluster','Broker','Streams','Metadata'] as $file)require_once __DIR__."/../src/$file.php";
function metaPayload(int $class,int $method,string $args):string{return pack('nnn',$class,$method,0).$args;}
function metaDeclare(string $name,int $bits=2,array $args=[]):string{return metaPayload(50,10,Codec::shortstr($name).chr($bits).Codec::writeTable(array_map(fn($k,$v)=>[$k,$v],array_keys($args),array_values($args))));}
function metaError(string $label,callable $fn,int $code):void{try{$fn();Harness::ok($label,false);}catch(RuntimeException $e){Harness::eq($label,$code,$e->getCode());}}
$dir=sys_get_temp_dir().'/qf-metadata-'.bin2hex(random_bytes(5));$store=new Store($dir.'/messages.log');$b=new Broker($store,$dir.'/users.json');$b->bootstrap('devpassword12');
try {
    $b->saveTopology();$before=$b->raftState('meta');$bytes=file_get_contents($dir.'/topology.json');$state=Metadata::amqp($b,91,1,50,10,metaDeclare('q',2,['x-queue-type'=>'quorum']),'admin');
    Harness::eq('queue declaration stages canonical kind','queue',$state['commands'][0]['kind']);Harness::eq('queue declaration carries raw arguments','quorum',$state['commands'][0]['data']['args']['x-queue-type']);Harness::eq('staging does not create queue',false,isset($b->queues['q']));Harness::eq('staging leaves topology file untouched',$bytes,file_get_contents($dir.'/topology.json'));Harness::eq('staging leaves metadata unchanged',$before,$b->raftState('meta'));
    $b->applyRaft('meta','queue',$state['commands'][0]['data'],1);Harness::ok('queue exists after explicit commit',isset($b->queues['q']));
    $again=Metadata::amqp($b,91,1,50,10,metaDeclare('q',2,['x-queue-type'=>'quorum']),'admin');Harness::eq('equivalent declare does not propose mutation',[],$again['commands']);
    metaError('inequivalent durability rejected before proposal',fn()=>Metadata::amqp($b,91,1,50,10,metaDeclare('q',0,['x-queue-type'=>'quorum']),'admin'),406);
    metaError('inequivalent queue arguments rejected',fn()=>Metadata::amqp($b,91,1,50,10,metaDeclare('q',2,['x-queue-type'=>'stream']),'admin'),406);
    metaError('non-durable quorum rejected',fn()=>Metadata::amqp($b,91,1,50,10,metaDeclare('bad',0,['x-queue-type'=>'quorum']),'admin'),406);
    metaError('negative TTL rejected',fn()=>Metadata::amqp($b,91,1,50,10,metaDeclare('bad',2,['x-message-ttl'=>-1]),'admin'),406);
    metaError('invalid leader locator rejected',fn()=>Metadata::amqp($b,91,1,50,10,metaDeclare('bad',2,['x-queue-leader-locator'=>'none']),'admin'),406);
    Harness::eq('passive declaration uses existing read path',null,Metadata::amqp($b,91,1,50,10,metaDeclare('q',3),'admin'));Harness::eq('exclusive declaration stays local',null,Metadata::amqp($b,91,1,50,10,metaDeclare('exclusive',6),'admin'));
    $generated=Metadata::amqp($b,91,1,50,10,metaDeclare(''),'admin');Harness::ok('anonymous name generated before commit',str_starts_with($generated['name'],'amq.gen-'));Harness::eq('generated name shared with committed row',$generated['name'],$generated['commands'][0]['data']['name']);
    Harness::eq('nowait suppresses response','',Metadata::amqp($b,91,1,50,10,metaDeclare('nowait',18),'admin')['response']);
    $b->putUser('reader','password1234',[]);$b->setPermissions('reader','/','^allowed$','^q$','^events$');metaError('permission failure stages no declaration',fn()=>Metadata::amqp($b,91,1,50,10,metaDeclare('denied'),'reader'),403);Harness::eq('denied queue remains absent',false,isset($b->queues['denied']));
    $b->declareExchange('events','topic');$b->topicPermissions['reader']['/']['events']=['write'=>'^private$','read'=>'^public$'];
    $bind=fn($key)=>metaPayload(50,20,Codec::shortstr('q').Codec::shortstr('events').Codec::shortstr($key).chr(0).Codec::writeTable([]));
    $binding=Metadata::amqp($b,91,1,50,20,$bind('public'),'reader');Harness::eq('binding uses portable exchange name','events',$binding['commands'][0]['data']['exchange']);Harness::eq('binding uses topic read rule','public',$binding['commands'][0]['data']['routingKey']);Harness::eq('binding not installed before commit',[],$b->bindings);metaError('topic read mismatch denied before proposal',fn()=>Metadata::amqp($b,91,1,50,20,$bind('private'),'reader'),403);
    $b->applyRaft('meta','binding',$binding['commands'][0]['data'],2);$unbind=Metadata::amqp($b,91,1,50,50,metaPayload(50,50,Codec::shortstr('q').Codec::shortstr('events').Codec::shortstr('public').Codec::writeTable([])),'reader');Harness::eq('unbind staged canonical kind','unbind',$unbind['commands'][0]['kind']);Harness::eq('unbind does not mutate bindings',1,count($b->bindings));
    $exPayload=fn($name,$kind,$bits=2)=>metaPayload(40,10,Codec::shortstr($name).Codec::shortstr($kind).chr($bits).Codec::writeTable([]));$ex=Metadata::amqp($b,91,1,40,10,$exPayload('new','direct'),'admin');Harness::eq('exchange canonical kind','direct',$ex['commands'][0]['data']['kind']);Harness::eq('exchange not created before commit',false,isset($b->exchanges['new']));metaError('exchange equivalence validated',fn()=>Metadata::amqp($b,91,1,40,10,$exPayload('events','fanout'),'admin'),406);metaError('unknown exchange type rejected',fn()=>Metadata::amqp($b,91,1,40,10,$exPayload('new','typo'),'admin'),503);
    $b->declareQueue('locked',[],true,true);$b->queues['locked']['owner']=2;metaError('exclusive ownership checked',fn()=>Metadata::amqp($b,91,1,50,40,metaPayload(50,40,Codec::shortstr('locked').chr(0)),'admin'),405);
    $b->enqueueLocal('q','body','body','','',false);metaError('conditional delete refuses ready queue',fn()=>Metadata::amqp($b,91,1,50,40,metaPayload(50,40,Codec::shortstr('q').chr(2)),'admin'),406);$delete=Metadata::amqp($b,91,1,50,40,metaPayload(50,40,Codec::shortstr('q').chr(0)),'admin');Harness::eq('delete stages canonical kind','delete_queue',$delete['commands'][0]['kind']);Harness::ok('delete does not remove queue before commit',isset($b->queues['q']));
    metaError('truncated short string rejected',fn()=>Metadata::amqp($b,91,1,50,10,pack('nnn',50,10,0).chr(5).'a','admin'),501);metaError('truncated table rejected',fn()=>Metadata::amqp($b,91,1,50,10,metaPayload(50,10,Codec::shortstr('bad').chr(2).pack('N',5)),'admin'),501);metaError('nested field length overflow rejected',fn()=>Metadata::amqp($b,91,1,50,10,metaPayload(50,10,Codec::shortstr('bad').chr(2).pack('N',4).chr(1).'xS'.chr(0)),'admin'),501);
    $shortField=Codec::shortstr('x-expires').'s'.pack('n',800);$shortPayload=metaPayload(50,10,Codec::shortstr('expiry-short').chr(2).pack('N',strlen($shortField)).$shortField);
    Harness::eq('signed short field preserves x-expires=800',800,Metadata::amqp($b,91,1,50,10,$shortPayload,'admin')['commands'][0]['data']['args']['x-expires']);
    $negativeField=Codec::shortstr('x-expires').'s'.pack('n',65535);metaError('negative signed short expires rejected',fn()=>Metadata::amqp($b,91,1,50,10,metaPayload(50,10,Codec::shortstr('expiry-short').chr(2).pack('N',strlen($negativeField)).$negativeField),'admin'),406);
    Harness::eq('read method is not intercepted',null,Metadata::amqp($b,91,1,60,70,'','admin'));
    Harness::done();
} finally {foreach($b->allBrokers() as $scope)if(is_resource($scope->store->fp))fclose($scope->store->fp);$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $p)$p->isDir()?rmdir($p->getPathname()):unlink($p->getPathname());rmdir($dir);}
