<?php
require_once __DIR__ . '/lib/Harness.php';
foreach (['Routing','Features','Policy','Codec','Auth','Store','Cluster','Broker','Streams'] as $f) require_once dirname(__DIR__) . "/src/$f.php";
$dir=sys_get_temp_dir().'/qf-proof-'.bin2hex(random_bytes(5));$store=new Store($dir.'/messages.log');$b=new Broker($store,$dir.'/users.json');$b->bootstrap('devpassword12');
try {
$b->declareQueue('q',['x-queue-type'=>'quorum']);$b->declareQueue('other',['x-queue-type'=>'quorum']);
$enq=['v'=>1,'vhost'=>'/','queue'=>'q','message_id'=>'m1','body_b64'=>base64_encode('0'),'persistent'=>true,'exchange'=>'amq.direct','routing_key'=>'r','headers'=>[['color','blue']],'propRaw'=>base64_encode("\0\0"),'priority'=>7,'expiration'=>100000];
$b->applyRaft('quorum','enq',$enq,1);$b->applyRaft('quorum','enq',$enq,1);
Harness::eq('repeat enq is idempotent',1,count($b->msgs));$m=current($b->msgs);Harness::eq('replicated headers preserved',[['color','blue']],$m['headers']);Harness::eq('priority preserved',7,$m['priority']);Harness::ok('TTL preserved',$m['expires']>0);Harness::eq('binary zero body preserved','0',$m['body']);
$snap=$b->raftState('quorum');Harness::eq('canonical enq snapshot message id','m1',$snap['queues'][0]['messages'][0]['message_id']);Harness::eq('shared group includes all queues',2,count($snap['queues']));
$b->enqueueLocal('other','stale','old','','',true);$b->getReady('q');$b->installRaftState('quorum',$snap);Harness::eq('snapshot clears omitted stale message',1,count($b->msgs));Harness::eq('snapshot rebuilds unacked ready',1,$b->readyCount('q'));
$b->installRaftState('quorum',$snap);Harness::eq('install replay does not duplicate',1,count($b->msgs));Harness::eq('installed disk has exactly one live body',1,count($store->replay()));
try{$b->installRaftState('quorum',['messages'=>[]]);Harness::ok('unknown quorum shape rejected',false);}catch(RuntimeException){Harness::eq('invalid snapshot leaves messages intact',1,count($b->msgs));}
$b->applyRaft('meta','binding',['vhost'=>'/','exchange'=>'amq.direct','queue'=>'q','routingKey'=>'rk','args'=>[]],2);Harness::eq('Bun binding names resolve',['q'],$b->route('amq.direct','rk'));
$b->applyRaft('meta','unbind',['vhost'=>'/','exchange'=>'amq.direct','queue'=>'q','routingKey'=>'rk','args'=>[]],3);Harness::eq('Bun unbind names resolve',[],$b->route('amq.direct','rk'));
foreach([['topic_permission',['user'=>'admin','exchange'=>'amq.topic','write'=>'a','read'=>'b']],['user_limits',['user'=>'admin','max-connections'=>2]],['global_parameter',['name'=>'g','value'=>['x'=>1]]],['policy',['name'=>'p','pattern'=>'^q$','apply_to'=>'queues','message_ttl_ms'=>50]],['parameter',['component'=>'federation-upstream','name'=>'u','value'=>['uri'=>'amqp://x']]]] as [$k,$d])$b->applyRaft('meta',$k,['vhost'=>'/',...$d],4);
Harness::eq('policy portable fields normalized',50,$b->queues['q']['args']['messageTtl']);$meta=$b->raftState('meta');Harness::eq('metadata users canonical rows','admin',$meta['users'][0]['name']);Harness::eq('settings included in snapshot',1,count($meta['topicPermissions']));
$b->declareQueue('stale');$b->installRaftState('meta',$meta);Harness::ok('metadata snapshot removes absent queue',!isset($b->queues['stale']));Harness::eq('metadata preserves canonical permissions','.*',$b->permissions['admin']['/']['read']);Harness::eq('metadata rebuilds policy',50,$b->queues['q']['args']['messageTtl']);Harness::eq('metadata rebuilds global parameters',['x'=>1],$b->parameters['global']['/']['g']);
$b->declareQueue('s',['x-queue-type'=>'stream']);$b->queues['s']['raftGroup']='q:s';$sa=['vhost'=>'/','queue'=>'s','ts'=>1234567,'body_b64'=>base64_encode('stream'),'exchange'=>'amq.direct','routing_key'=>'key','headers'=>[['h',false]],'propRaw'=>base64_encode("\0\0")];$b->applyRaft('q:s','sappend',$sa,9);$ss=$b->raftState('q:s');Harness::eq('stream canonical timestamp',1234567,$ss['stream']['entries'][0]['ts']);Harness::eq('stream exchange kept','amq.direct',$ss['stream']['entries'][0]['exchange']);Harness::eq('stream snapshot index',9,$ss['stream']['raftIndex']);
$b->installRaftState('q:s',$ss);$b->applyRaft('q:s','sappend',$sa,9);Harness::eq('installed snapshot skips index replay',1,$b->streamNext('s'));
$streamDir=$dir.'/streams/'.bin2hex('s');$restart=new Streams($streamDir);$restart->append('duplicate',[],null,null,null,'q:s',9);Harness::eq('snapshot index is durable after reopen',1,$restart->next());Harness::eq('snapshot records survive reopen','stream',$restart->read(0,1)[0]['body']);
try{$restart->install(['records'=>[]]);Harness::ok('unknown stream shape rejected',false);}catch(RuntimeException){Harness::eq('unknown stream shape does not delete data',1,$restart->next());}
$empty=['stream'=>['vhost'=>'/','queue'=>'s','first'=>10,'next'=>10,'raftIndex'=>15,'entries'=>[]]];$restart->install($empty,'q:s');$after=new Streams($streamDir);Harness::eq('empty retained stream preserves next after reopen',10,$after->next());$after->append('no',[],null,null,null,'q:s',14);Harness::eq('empty stream preserves applied index after reopen',10,$after->next());
$sd=$dir.'/sequence';$x=new Streams($sd);$x->append('one',[],null,'publisher',1);$x->storeOffset('consumer',0);$x->append('two',[],null,'publisher',2);$y=new Streams($sd);Harness::eq('stale sidecar cannot regress sequence',2,$y->sequence('publisher'));$y->append('dup',[],null,'publisher',2);Harness::eq('stale sidecar retry does not duplicate',2,$y->next());
$b->declareExchange('source','direct');$b->declareExchange('destination','direct');$b->bindExchange('destination','source','shared');$b->bind('q','destination','shared');
$portable=$b->raftState('meta');Harness::eq('exchange bindings use separate portable collection',1,count($portable['exchangeBindings']));Harness::ok('queue binding rows remain Rust-compatible',count(array_filter($portable['bindings'],static fn($row)=>!isset($row['exchange'],$row['queue'])))===0);
$b->installRaftState('meta',$portable);Harness::eq('exchange binding snapshot restores routing',['q'],$b->route('source','shared'));Harness::eq('exchange binding keeps routing key','shared',$b->e2e[0]['key']);
$invalid=$portable;$invalid['exchangeBindings']=['invalid'];try{$b->installRaftState('meta',$invalid);Harness::ok('invalid exchange bindings rejected',false);}catch(RuntimeException){Harness::eq('invalid exchange binding leaves topology intact',['q'],$b->route('source','shared'));}
Harness::eq('raft application guard restored',false,$b->raftApplying);
Harness::done();
} finally { $it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $p)$p->isDir()?rmdir($p->getPathname()):unlink($p->getPathname());rmdir($dir); }
